//Generated by pr0ntools on 10/07/2011 13:27:38
//transdefs.js version 1.0

var segdefs_ver = "1.0";
var transdefs = [
['t1',3,3,2,[178,203,245,366],[0,0,0,0,0],true],
['t2',1,3,4,[180,205,92,213],[0,0,0,0,0],false],
]
